In [ ]:
#Q1). Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
np.arr = ([0, 1, 2, 3, 4, 5])
arr
type(arr)

list

In [ ]:
# Q2)Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
arr = is_float64 = arr.dtype == np.float64


In [ ]:
arr

True

In [ ]:
#Q3). Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np

# Create a NumPy array with a data type of complex128 containing three complex numbers
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print(arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


In [ ]:
#Q4). Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


In [ ]:
#Q5). Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


arr = np.array([1.123456789, 2.123456789, 3.123456789], dtype=np.float64)
arr_float32 = arr.astype(np.float32)


print(arr_float32)
print(arr_float32.dtype)


[1.1234568 2.1234567 3.1234567]
float32


In [ ]:
#Q6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype

    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
#Q7). Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np

def array_dimension(arr):
    """
    Takes a NumPy array as input and returns its dimensionality.

    Parameters:
    arr (np.ndarray): Input NumPy array

    Returns:
    int: The dimensionality of the array
    """
    return arr.ndim

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensionality = array_dimension(arr)
print("Dimensionality:", dimensionality)


Dimensionality: 2


In [ ]:
#Q8). Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes

    return item_size, total_size


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item Size (bytes):", item_size)
print("Total Size (bytes):", total_size)

Item Size (bytes): 8
Total Size (bytes): 48


In [ ]:
#Q9). Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))


(24, 8)


In [ ]:
#Q10). Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (24, 8)


In [ ]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

# Example usage
n = 8
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
rows = 5
cols = 7
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[1 3 5 7 9]


In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)


[1 2 3 4 5]


In [ ]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


In [ ]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along the first axis (rows)
concatenated_array_axis_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis_0)

# Concatenate along the second axis (columns)
concatenated_array_axis_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.
import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])  # shape: (2, 2)
arr2 = np.array([[5], [6]])       # shape: (2, 1)

# Concatenate along the second axis (horizontally)
concatenated_array = np.concatenate((arr1, arr2), axis=1)

# Print the original arrays and the concatenated array
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated array horizontally:\n", concatenated_array)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5]
 [6]]
Concatenated array horizontally:
 [[1 2 5]
 [3 4 6]]


In [ ]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np

def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

stacked_array = stack_arrays_vertically([arr1, arr2])
print("Stacked array:\n", stacked_array)


Stacked array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size. import numpy as np

def generate_integer_range(start, stop, step=1):
    return np.arange(start, stop + 1, step, dtype=int)

# Example usage
start = 1
stop = 10
step = 2
result_array = generate_integer_range(start, stop, step)
print(result_array)


[1 3 5 7 9]


In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

# Example usage
result_array = generate_equally_spaced_values()
print(result_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5)

# Example usage
result_array = generate_logarithmically_spaced_values()
print(result_array)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd

np.random.seed(0)  # Setting seed for reproducibility
random_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(random_array, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  45  48  65
1  68  68  10
2  84  22  37
3  88  71  89
4  89  13  59


In [ ]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


data = {
    'A': [1, 2, -3, 4, -5],
    'B': [10, -20, 30, -40, 50]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)


df_modified = replace_negatives_with_zeros(df, 'B')

print("\nDataFrame after replacing negatives with zeros in column 'B':")
print(df_modified)


Original DataFrame:
   A   B
0  1  10
1  2 -20
2 -3  30
3  4 -40
4 -5  50

DataFrame after replacing negatives with zeros in column 'B':
   A   B
0  1  10
1  2   0
2 -3  30
3  4   0
4 -5  50


In [ ]:
#26. Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])


arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("Third element:", third_element)


Third element: 30


In [ ]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array. arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at index (1, 2)
element_12 = arr_2d[1, 2]

print("Element at index (1, 2):", element_12)


Element at index (1, 2): 6


/opt/conda/lib/python3.10/site-packages/IPython/core/inputtransformer2.py:604: UserWarning: `make_tokens_by_line` received a list of lines which do not have lineending markers ('\n', '\r', '\r\n', '\x0b', '\x0c'), behavior will be unspecified
  tokens_by_line = make_tokens_by_line(lines)


In [ ]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array. arr = np.array([3, 8, 2, 10, 5, 7])

arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
result = arr[mask]

print("Elements greater than 5:", result)


Elements greater than 5: [ 8 10  7]


In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Sliced array:", sliced_array)


Sliced array: [3 4 5 6]


In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array. arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the 2D array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)


Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np

def extract_elements_from_indices(arr_2d, indices):
    # Use advanced indexing to extract elements from arr_2d based on indices
    return arr_2d[indices[:, 0], indices[:, 1]]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices array specifying row and column indices
indices = np.array([[0, 0],
                    [1, 2],
                    [2, 1]])

# Extract elements from arr_2d based on indices
result = extract_elements_from_indices(arr_2d, indices)

print("Extracted elements based on indices:")
print(result)


Extracted elements based on indices:
[1 6 8]


In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


def filter_elements_above_threshold(arr, threshold):
    # Create a boolean mask for elements greater than the threshold
    mask = arr > threshold

    # Use boolean indexing to filter elements
    filtered_array = arr[mask]

    return filtered_array

# Example usage
arr = np.array([1, 10, 3, 20, 5, 30])
threshold = 10

filtered_elements = filter_elements_above_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", filtered_elements)


Filtered elements greater than 10 : [20 30]


In [ ]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    # Use advanced indexing to extract elements from arr_3d based on indices
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]

# Example usage
arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

# Indices arrays specifying indices for each dimension
indices_dim1 = np.array([[0, 1],
                         [1, 0]])

indices_dim2 = np.array([[0, 2],
                         [1, 1]])

indices_dim3 = np.array([[1, 0],
                         [2, 2]])

# Extract elements from arr_3d based on indices
result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)

print("Extracted elements based on indices:")
print(result)


Extracted elements based on indices:
[[ 2 16]
 [15  6]]


In [2]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np
import numpy as np

def filter_elements(arr, a, b):
    """
    Returns elements from the array `arr` that are greater than `a` and less than `b`.

    Parameters:
    arr (np.ndarray): Input array
    a (float): Lower bound condition
    b (float): Upper bound condition

    Returns:
    np.ndarray: Array with elements satisfying both conditions
    """
    return arr[(arr > a) & (arr < b)]

# Example usage:
arr = np.array([1, 5, 10, 15, 20, 25])
a = 5
b = 20

filtered_elements = filter_elements(arr, a, b)
print(filtered_elements)


[10 15]


In [3]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements(arr, row_indices, col_indices):

    return arr[row_indices, col_indices]

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

extracted_elements = extract_elements(arr, row_indices, col_indices)
print(extracted_elements)


[3 5 7]


In [5]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

def add_scalar(arr, scalar):

    return arr + scalar

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

scalar = 5

new_arr = add_scalar(arr, scalar)
print(new_arr)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np

def multiply_rows(arr1, arr2):

    return arr1.T * arr2

# Example usage:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = multiply_rows(arr1, arr2)
print(result)


[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [8]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

def add_to_rows(arr1, arr2):

    return arr1.T + arr2

# Example usage:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

# Reshape arr1 to match broadcasting rules
arr1_reshaped = arr1.T

result = add_to_rows(arr1_reshaped, arr2)
print(result)


ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

In [9]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

def add_arrays(arr1, arr2):


    return arr1 + arr2

# Example usage:
arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[4, 5, 6]])

result = add_arrays(arr1, arr2)
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [10]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
import numpy as np

def multiply_arrays(arr1, arr2):

    # Reshape arr2 to (2, 2, 1) to broadcast correctly with arr1 of shape (2, 3)
    arr2_expanded = arr2[:, :, np.newaxis]

    # Perform element-wise multiplication using broadcasting
    result = arr1 * arr2_expanded

    return result

# Example usage:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

result = multiply_arrays(arr1, arr2)
print(result)


[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [11]:
#41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def column_wise_mean(arr):

    return np.mean(arr, axis=0)

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_means = column_wise_mean(arr)
print(column_means)


[2.5 3.5 4.5]


In [12]:
#42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def row_wise_max(arr):

    return np.max(arr, axis=1)

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = row_wise_max(arr)
print(row_max)


[3 6]


In [13]:
#43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def column_wise_max_indices(arr):

    return np.argmax(arr, axis=0)

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_max_indices = column_wise_max_indices(arr)
print(col_max_indices)


[1 1 1]


In [14]:
#44. For the given array, apply custom function to calculate moving sum along rows. arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def moving_sum_along_rows(arr, window_size):

    # Initialize an array to store the results
    result = np.zeros_like(arr, dtype=np.float64)

    # Iterate over each row
    for i in range(arr.shape[0]):
        # Calculate cumulative sum with specified window size
        cumsum = np.cumsum(arr[i])

        # Calculate moving sum by shifting the cumulative sum
        result[i, window_size-1:] = cumsum[window_size-1:] - cumsum[:-window_size]

    return result

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
window_size = 2

moving_sum = moving_sum_along_rows(arr, window_size)
print(moving_sum)


[[ 0.  2.  5.]
 [ 0.  5. 11.]]


In [15]:
#45. In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np

def check_all_even_columns(arr):

    # Check if all elements in each column are even
    all_even = np.all(arr % 2 == 0, axis=0)

    return all_even

# Example usage:
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even_columns = check_all_even_columns(arr)
print(all_even_columns)


[False False False]


In [16]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])
import numpy as np

def reshape_array(arr, m, n):

    return np.reshape(arr, (m, n))

# Example usage:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3

reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [17]:
#47. Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def flatten_matrix(matrix):

    return matrix.flatten()

# Example usage:
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [18]:
#48. Write a function that concatenates two given arrays along a specified axis. array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])
import numpy as np

def concatenate_arrays(array1, array2, axis=0):

    return np.concatenate((array1, array2), axis=axis)

# Example usage:
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_axis0)

# Concatenate along axis 1 (columns)
concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:")
print(concatenated_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


/usr/local/lib/python3.10/dist-packages/IPython/core/inputtransformer2.py:478: UserWarning: `make_tokens_by_line` received a list of lines which do not have lineending markers ('\n', '\r', '\r\n', '\x0b', '\x0c'), behavior will be unspecified
  warnings.warn("`make_tokens_by_line` received a list of lines which do not have lineending markers ('\\n', '\\r', '\\r\\n', '\\x0b', '\\x0c'), behavior will be unspecified")


In [19]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis. original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
import numpy as np

def split_array(original_array, axis=0, indices_or_sections=2):


    return np.split(original_array, indices_or_sections, axis=axis)

# Example usage:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Split along axis 0 (rows) into 3 sub-arrays
split_arrays_axis0 = split_array(original_array, axis=0, indices_or_sections=3)
print("Split along axis 0:")
for arr in split_arrays_axis0:
    print(arr)

# Split along axis 1 (columns) into 3 sub-arrays
split_arrays_axis1 = split_array(original_array, axis=1, indices_or_sections=3)
print("\nSplit along axis 1:")
for arr in split_arrays_axis1:
    print(arr)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [20]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]
import numpy as np

def insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):

    # Insert elements at specified indices
    for idx, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, value)

    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)

    return original_array

# Example usage:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10 11  4  5]


In [23]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
import numpy as np

# Generate arr1 with random integers
arr1 = np.random.randint(1, 100, size=(5, 5))  # Example: random integers between 1 and 100, 5x5 array

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


ValueError: operands could not be broadcast together with shapes (5,5) (10,) 

In [24]:
import numpy as np

# Generate arr1 with random integers
arr1 = np.random.randint(1, 100, size=(5, 5))  # Example: random integers between 1 and 100, 5x5 array

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11).reshape((1,10)) # Reshape arr2 to be compatible for broadcasting

# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)

ValueError: operands could not be broadcast together with shapes (5,5) (1,10) 

In [25]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction between arr1 and arr2
result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [26]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
import numpy as np

# Generate arr1 with random integers
arr1 = np.random.randint(1, 10, size=(5, 5))  # Example: random integers between 1 and 10, 5x5 array

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication between arr1 and arr2
result = arr1 * arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


arr1:
[[5 1 9 2 7]
 [2 5 9 9 1]
 [5 2 2 8 5]
 [2 3 4 4 1]
 [3 4 3 5 2]]

arr2:
[1 2 3 4 5]

Result of element-wise multiplication:
[[ 5  2 27  8 35]
 [ 2 10 27 36  5]
 [ 5  4  6 32 25]
 [ 2  6 12 16  5]
 [ 3  8  9 20 10]]


In [27]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division between arr1 and arr2
result = arr1 / arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)


arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [28]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Create arr2 as the reverse of arr1
arr2 = arr1[::-1]

# Perform element-wise exponentiation between arr1 and arr2
result = arr1 ** arr2  # or np.power(arr1, arr2)

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)


arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [29]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np

def count_substring_occurrences(arr, substring):

    # Vectorized operation to count occurrences of substring in each element of arr
    counts = np.char.count(arr.astype(str), substring)

    # Summing up the counts across all elements in the array
    total_count = np.sum(counts)

    return total_count

# Example usage:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

occurrences = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}' in the array: {occurrences}")


Occurrences of 'hello' in the array: 3


In [30]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
import numpy as np

def extract_uppercase_chars(arr):

    # Initialize an empty list to store uppercase characters
    uppercase_chars = []

    # Iterate through each string in the array
    for string in arr:
        # Iterate through each character in the string
        for char in string:
            # Check if the character is uppercase
            if char.isupper():
                # Append the uppercase character to the list
                uppercase_chars.append(char)

    return uppercase_chars

# Example usage:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_chars = extract_uppercase_chars(arr)
print("Uppercase characters extracted:", uppercase_chars)


Uppercase characters extracted: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [31]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def replace_substring(arr, old_substring, new_substring):

    # Vectorized operation to replace old_substring with new_substring in each element of arr
    return np.char.replace(arr, old_substring, new_substring)

# Example usage:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

modified_arr = replace_substring(arr, old_substring, new_substring)
print("Modified array:")
print(modified_arr)


Modified array:
['orange' 'banana' 'grape' 'pineorange']


In [32]:
#59. Write a function that concatenates strings in a NumPy array element-wise. arr1 = np.array(['Hello', 'World'])
 arr2 = np.array(['Open', 'AI'])
import numpy as np

def concatenate_strings(arr1, arr2):

    # Vectorized operation to concatenate strings element-wise
    return np.char.add(arr1, arr2)

# Example usage:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:")
print(concatenated_arr)


Concatenated array:
['HelloOpen' 'WorldAI']


/usr/local/lib/python3.10/dist-packages/IPython/core/inputtransformer2.py:478: UserWarning: `make_tokens_by_line` received a list of lines which do not have lineending markers ('\n', '\r', '\r\n', '\x0b', '\x0c'), behavior will be unspecified
  warnings.warn("`make_tokens_by_line` received a list of lines which do not have lineending markers ('\\n', '\\r', '\\r\\n', '\\x0b', '\\x0c'), behavior will be unspecified")


In [33]:
#60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple']) arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def longest_string_length(arr):

    # Vectorized operation to compute lengths of all strings in arr
    lengths = np.vectorize(len)(arr)

    # Find and return the maximum length
    return np.max(lengths)

# Example usage:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

longest_length = longest_string_length(arr)
print(f"Length of the longest string in the array: {longest_length}")


Length of the longest string in the array: 9


In [34]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

# Print results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [ 685  560  630  193  836  764  708  360   10  724  278  755  805  600
   71  473  601  397  315  706  487  552   88  175  601  850  678  538
  846   73  778  917  116  977  756  710  848  432  449  851  100  985
  178  756  798  660  148  911  424  289  962  266  698  640  545  544
  715  245  152  676  511  460  883  184   29  803  129  129  933   54
  902  551  489  757  274  336  389  618   43  443  544  889  258  322
 1000  938   58  292  871  120  780  431   83   92  897  399  612  566
  909  634]
Mean: 524.97
Median: 551.5
Variance: 82414.08910000001
Standard Deviation: 287.07854169199067


In [35]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Calculate 25th and 75th percentiles
percentile_25th = np.percentile(dataset, 25)
percentile_75th = np.percentile(dataset, 75)

# Print results
print("Dataset:", dataset)
print("25th Percentile:", percentile_25th)
print("75th Percentile:", percentile_75th)


Dataset: [ 45  48  65  68  68  10  84  22  37  88  71  89  89  13  59  66  40  88
  47  89  82  38  26  78  73  10  21  81  70  80  48  65  83 100  89  50
  30  20  20  15  40  33  66  10  58  33  32  75  24  36]
25th Percentile: 32.25
75th Percentile: 77.25


In [36]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
import numpy as np

# Example arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute correlation coefficient between array1 and array2
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient from the matrix
correlation_coefficient = correlation_matrix[0, 1]

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)


Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Correlation Coefficient between array1 and array2: -0.9999999999999999


In [37]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication using dot function
result_matrix = np.dot(matrix1, matrix2)

# Print the matrices and the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [38]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate array of 50 random integers between 10 and 1000
dataset = np.random.randint(10, 1001, size=50)

# Calculate percentiles and quartiles
percentile_10th = np.percentile(dataset, 10)
percentile_50th = np.percentile(dataset, 50)  # Median
percentile_90th = np.percentile(dataset, 90)
quartile_1st = np.percentile(dataset, 25)  # First quartile (25th percentile)
quartile_3rd = np.percentile(dataset, 75)  # Third quartile (75th percentile)

# Print results
print("Dataset:", dataset)
print("10th Percentile:", percentile_10th)
print("50th Percentile (Median):", percentile_50th)
print("90th Percentile:", percentile_90th)
print("First Quartile (25th Percentile):", quartile_1st)
print("Third Quartile (75th Percentile):", quartile_3rd)


Dataset: [694 569 639 202 845 773 717 369  19 733 287 764 814 609  80 482 610 406
 324 715 496 561  97 184 610 859 687 547 855  82 787 926 125 986 765 719
 857 441 458 860 109 994 187 765 807 669 157 920 433 298]
10th Percentile: 123.4
50th Percentile (Median): 610.0
90th Percentile: 859.1
First Quartile (25th Percentile): 335.25
Third Quartile (75th Percentile): 771.0


In [39]:
#66. Create a NumPy array of integers and find the index of a specific element.
import numpy as np

# Example NumPy array of integers
arr = np.array([2, 4, 6, 8, 10, 12, 14])

# Element to find the index
element = 10

# Find index of the element using np.where
index = np.where(arr == element)[0]

# Print the index
if len(index) > 0:
    print(f"Index of {element}:", index[0])
else:
    print(f"{element} not found in the array.")


Index of 10: 4


In [40]:
#67. Generate a random NumPy array and sort it in ascending order.
import numpy as np

# Generate a random NumPy array
np.random.seed(0)  # Set seed for reproducibility
random_array = np.random.randint(1, 100, size=10)  # Generating 10 random integers between 1 and 100

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Print the original and sorted arrays
print("Original array:")
print(random_array)
print("\nSorted array in ascending order:")
print(sorted_array)


Original array:
[45 48 65 68 68 10 84 22 37 88]

Sorted array in ascending order:
[10 22 37 45 48 65 68 68 84 88]


In [41]:
#68. Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

# Print the filtered array
print("Filtered elements greater than 20:")
print(filtered_array)


Filtered elements greater than 20:
[25 42 30]


In [42]:
#69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15])
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

# Print the filtered array
print("Elements divisible by 3:")
print(filtered_array)


Elements divisible by 3:
[12 15]


In [43]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_array = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Elements between 20 and 40 (inclusive):")
print(filtered_array)


Elements between 20 and 40 (inclusive):
[20 30 40]


In [44]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using dtype attribute byteorder
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byte_order)


Byte order of the array: =


In [45]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`. arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the array after byte swapping
print("Array after byte swapping:")
print(arr)


Array after byte swapping:
[16777216 33554432 50331648]


In [46]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
arr_swapped = arr.newbyteorder()

# Print the original and swapped arrays
print("Original array:")
print(arr)
print("\nArray with swapped byte order:")
print(arr_swapped)


Original array:
[1 2 3]

Array with swapped byte order:
[16777216 33554432 50331648]


In [47]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system byte order
system_byteorder = sys.byteorder

# Swap byte order conditionally based on system endianness
if system_byteorder == 'little':
    arr_swapped = arr.newbyteorder('big')
else:
    arr_swapped = arr.newbyteorder('little')

# Print the original and swapped arrays
print("Original array:")
print(arr)
print("\nArray with swapped byte order based on system endianness:")
print(arr_swapped)


Original array:
[1 2 3]

Array with swapped byte order based on system endianness:
[16777216 33554432 50331648]


In [48]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`. arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary based on system byte order
current_byteorder = arr.dtype.byteorder
system_byteorder = np.dtype(np.int32).byteorder

# Determine if byte swapping is necessary
byte_swapping_needed = (current_byteorder != system_byteorder)

# Print the result
if byte_swapping_needed:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Byte swapping is not necessary.


In [49]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a deep copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("arr1:", arr1)
print("copy_arr:", copy_arr)


arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [50]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
import numpy as np

# Create a 2D NumPy array matrix of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:")
print(matrix)

# Extract a slice view_slice from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Print the modified view_slice and the original matrix
print("\nModified view_slice:")
print(view_slice)

print("\nOriginal matrix after modification:")
print(matrix)


Original matrix:
[[7 9 9]
 [2 7 8]
 [8 9 2]]

Modified view_slice:
[[100   8]
 [  9   2]]

Original matrix after modification:
[[  7   9   9]
 [  2 100   8]
 [  8   9   2]]


In [51]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
import numpy as np

# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array_a:")
print(array_a)

# Extract a slice view_b from array_a
view_b = array_a[1:3, 1:3]
print("\nSlice view_b:")
print(view_b)

# Broadcast addition of 5 to view_b
view_b += 5

# Print modified view_b and original array_a
print("\nModified view_b after broadcasting addition of 5:")
print(view_b)

print("\nOriginal array_a after modification:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice view_b:
[[5 6]
 [8 9]]

Modified view_b after broadcasting addition of 5:
[[10 11]
 [13 14]]

Original array_a after modification:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [52]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
import numpy as np

# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original orig_array:")
print(orig_array)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view reshaped_view:")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Print modified reshaped_view and original orig_array
print("\nModified reshaped_view:")
print(reshaped_view)

print("\nOriginal orig_array after modification:")
print(orig_array)


Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view reshaped_view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original orig_array after modification:
[[100   2   3   4]
 [  5   6   7   8]]


In [53]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data
import numpy as np

# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))
print("Original data:")
print(data)

# Create a copy data_copy of elements greater than 5
data_copy = data[data > 5].copy()
print("\nCopy data_copy of elements greater than 5:")
print(data_copy)

# Modify an element in data_copy
data_copy[0] = 100

# Verify if modifying data_copy affects the original data
print("\nModified data_copy:")
print(data_copy)

print("\nOriginal data after modification:")
print(data)


Original data:
[[6 9 5 4]
 [1 4 6 1]
 [3 4 9 2]]

Copy data_copy of elements greater than 5:
[6 9 6 9]

Modified data_copy:
[100   9   6   9]

Original data after modification:
[[6 9 5 4]
 [1 4 6 1]
 [3 4 9 2]]


In [55]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
import numpy as np

# Create matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform addition and subtraction operations between A and B
addition_result = A + B
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition Result (A + B):")
print(addition_result)

print("\nSubtraction Result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition Result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction Result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [56]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
import numpy as np

# Generate matrices C (3x2) and D (2x4)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication using np.dot()
result = np.dot(C, D)

# Print the matrices and the result
print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix Multiplication Result (C dot D):")
print(result)


Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result (C dot D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [57]:
#83. Create a matrix `E` and find its transpose.
import numpy as np

# Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6]])

# Find the transpose of matrix E using .T attribute
E_transpose = E.T

# Alternatively, find the transpose of matrix E using np.transpose()
# E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of E:
[[1 4]
 [2 5]
 [3 6]]


In [58]:
#84. Generate a square matrix `F` and compute its determinant.
import numpy as np

# Generate a square matrix F
F = np.array([[1, 2],
              [3, 4]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F:")
print(F)

print("\nDeterminant of F:")
print(determinant_F)


Matrix F:
[[1 2]
 [3 4]]

Determinant of F:
-2.0000000000000004


In [59]:
#85. Create a square matrix `G` and find its inverse.
import numpy as np

# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Find the inverse of matrix G using np.linalg.inv()
inverse_G = np.linalg.inv(G)

# Print the matrix and its inverse
print("Matrix G:")
print(G)

print("\nInverse of G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of G:
[[-2.   1. ]
 [ 1.5 -0.5]]
